# Generated by Django 3.2.7 on 2021-10-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='dir_way',
            field=models.FileField(upload_to='photo/'),
        ),
    ]
