# Generated by Django 3.2.7 on 2021-10-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttry', '0002_alter_photo_dir_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='dir_way',
            field=models.FileField(upload_to='static/image/photo/'),
        ),
    ]
