# Generated by Django 3.2.7 on 2021-10-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttry', '0005_ask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='date',
            field=models.DateTimeField(verbose_name='Дата загрузки'),
        ),
    ]
