# Generated by Django 3.2.7 on 2021-10-28 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firsttry', '0006_alter_ask_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otchets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отчёта')),
                ('date', models.DateField(verbose_name='Дата загрузки')),
                ('text', models.TextField(verbose_name='Текст отчета')),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='date',
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название фото/видео'),
        ),
        migrations.AddField(
            model_name='photo',
            name='otchet',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='firsttry.otchets', verbose_name='Название отчёта'),
            preserve_default=False,
        ),
    ]
