# Generated by Django 3.2.7 on 2021-10-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttry', '0007_auto_20211028_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Название фото/видео'),
        ),
    ]
