# Generated by Django 3.2.7 on 2021-10-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttry', '0008_alter_photo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(default='Неизвестное', max_length=100, null=True, verbose_name='Название фото/видео'),
        ),
    ]
