# Generated by Django 3.2.7 on 2021-11-09 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firsttry', '0010_url_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum_Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тема обсуждения')),
                ('theme', models.CharField(max_length=100, verbose_name='Принадлежность к теме форума')),
                ('start_data', models.DateTimeField(verbose_name='Дата создания обсуждения')),
                ('user', models.CharField(default='Анонимный охотник', max_length=30, verbose_name='Автор топика')),
                ('text', models.TextField(verbose_name='Разъяснение обсуждения')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Дата создания обсуждения')),
                ('user', models.CharField(default='Анонимный охотник', max_length=30, verbose_name='Автор комментария')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('quetion', models.IntegerField(verbose_name='Номер комментария-вопроса')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firsttry.otchets', verbose_name='Принадлежность к обсуждению')),
            ],
        ),
    ]
