# Generated by Django 3.2.7 on 2021-11-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttry', '0011_comment_forum_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='quetion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер комментария-вопроса'),
        ),
    ]
