# Generated by Django 3.2.7 on 2021-12-06 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firsttry', '0015_auto_20211125_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Фамилия')),
                ('info', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('sex', models.BooleanField(blank=True, null=True, verbose_name='Мужчина?')),
                ('ava', models.FileField(default='profiles/ava.jpg', upload_to='profiles/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
