# Generated by Django 3.2.7 on 2021-12-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firsttry', '0017_alter_userinfo_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
