# Generated by Django 3.2.7 on 2021-12-06 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firsttry', '0019_auto_20211206_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_topic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор топика'),
        ),
    ]
