# Generated by Django 3.2.7 on 2021-12-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttry', '0020_alter_forum_topic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ava',
            field=models.FileField(default='profiles/ava.jpg', upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='forum_topic',
            name='ava',
            field=models.FileField(default='profiles/ava.jpg', upload_to='profiles/'),
        ),
    ]
