# Generated by Django 3.2.7 on 2021-12-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttry', '0021_auto_20211206_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ava',
            field=models.FileField(default='profiles/ava.jpg', upload_to='profiles/', verbose_name='Аватарка'),
        ),
    ]
