# Generated by Django 3.2.7 on 2021-10-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttry', '0003_alter_photo_dir_way'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_video',
            field=models.BooleanField(default=0, verbose_name='Видео?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateField(verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='dir_way',
            field=models.FileField(upload_to='static/image/photo/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название отчёта'),
        ),
    ]
