# Generated by Django 3.2.7 on 2021-10-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttry', '0004_auto_20211020_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тема вопроса')),
                ('date', models.DateField(verbose_name='Дата загрузки')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта отправителя')),
                ('quetion', models.TextField(verbose_name='Вопрос')),
            ],
        ),
    ]
