# Generated by Django 3.2.7 on 2021-10-29 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firsttry', '0009_alter_photo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Неизвестное', max_length=100, null=True, verbose_name='Название фото/видео')),
                ('dir_way', models.URLField(verbose_name='Ссылка на видео')),
                ('otchet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firsttry.otchets', verbose_name='Название отчёта')),
            ],
        ),
    ]
