# Generated by Django 3.2.7 on 2021-11-13 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firsttry', '0012_alter_comment_quetion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firsttry.forum_topic', verbose_name='Принадлежность к обсуждению'),
        ),
    ]
